# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Ryan Grosso
email: 1grossora@gmail.com
linkedin_username: https://www.linkedin.com/in/ryan-grosso-811542131/
instagram_username: https://www.instagram.com/groryangro/?hl=en
github_username: https://github.com/1grossora
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: (845) 220-6000
copyright: Ryan Grosso

# API settings
google_api_key: AIzaSyAkGyPVUIZuC9dKOqiuquwxQENQio5PhPA

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title
